apiVersion: v1
kind: ReplicationController
metadata:
  name: postgres
  namespace: kong
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:9.6
          env:
            - name: POSTGRES_USER
              value: kong
            - name: POSTGRES_PASSWORD
              value: kong
            - name: POSTGRES_DB
              value: kong
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pg-data
      volumes:
        - name: pg-data
          emptyDir: {}
---
kind: "Pod"
apiVersion: "v1"
metadata:
  name: "eap-app66-1-pjdjd"
  generateName: "eap-app66-1-"
  namespace: "baik"
  selfLink: "/api/v1/namespaces/baik/pods/eap-app66-1-pjdjd"
  uid: "ab7f3984-1c6c-4638-9a19-3f4c9b8a669b"
  resourceVersion: "485215"
  creationTimestamp: "2021-07-30T09:43:10Z"
  labels:
    application: "eap-app66"
    cone/create.name: "template_eap73-basic-s2i_20210730063556214"
    deployment: "eap-app66-1"
    deploymentConfig: "eap-app66"
    deploymentconfig: "eap-app66"
  annotations:
    k8s.v1.cni.cncf.io/network-status: "[{\n    \"name\": \"\",\n    \"interface\"\
      : \"eth0\",\n    \"ips\": [\n        \"10.131.0.94\"\n    ],\n    \"default\"\
      : true,\n    \"dns\": {}\n}]"
    k8s.v1.cni.cncf.io/networks-status: "[{\n    \"name\": \"\",\n    \"interface\"\
      : \"eth0\",\n    \"ips\": [\n        \"10.131.0.94\"\n    ],\n    \"default\"\
      : true,\n    \"dns\": {}\n}]"
    openshift.io/deployment-config.latest-version: "1"
    openshift.io/deployment-config.name: "eap-app66"
    openshift.io/deployment.name: "eap-app66-1"
    openshift.io/scc: "restricted"
  ownerReferences:
  - apiVersion: "v1"
    kind: "ReplicationController"
    name: "eap-app66-1"
    uid: "377d2661-5b41-49a6-bc2a-1224db3c7bb9"
    controller: true
    blockOwnerDeletion: true
  managedFields:
  - manager: "kube-controller-manager"
    operation: "Update"
    apiVersion: "v1"
    time: "2021-07-30T09:43:10Z"
    fieldsType: "FieldsV1"
    fieldsV1:
      f:metadata:
        f:annotations:
          ".": {}
          f:openshift.io/deployment-config.latest-version: {}
          f:openshift.io/deployment-config.name: {}
          f:openshift.io/deployment.name: {}
        f:generateName: {}
        f:labels:
          ".": {}
          f:application: {}
          f:cone/create.name: {}
          f:deployment: {}
          f:deploymentConfig: {}
          f:deploymentconfig: {}
        f:ownerReferences:
          ".": {}
          k:{"uid":"377d2661-5b41-49a6-bc2a-1224db3c7bb9"}:
            ".": {}
            f:apiVersion: {}
            f:blockOwnerDeletion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:containers:
          k:{"name":"eap-app66"}:
            ".": {}
            f:env:
              ".": {}
              k:{"name":"AUTO_DEPLOY_EXPLODED"}:
                ".": {}
                f:name: {}
                f:value: {}
              k:{"name":"ENABLE_GENERATE_DEFAULT_DATASOURCE"}:
                ".": {}
                f:name: {}
                f:value: {}
              k:{"name":"JGROUPS_CLUSTER_PASSWORD"}:
                ".": {}
                f:name: {}
                f:value: {}
              k:{"name":"JGROUPS_PING_PROTOCOL"}:
                ".": {}
                f:name: {}
                f:value: {}
              k:{"name":"MQ_CLUSTER_PASSWORD"}:
                ".": {}
                f:name: {}
                f:value: {}
              k:{"name":"MQ_QUEUES"}:
                ".": {}
                f:name: {}
              k:{"name":"MQ_TOPICS"}:
                ".": {}
                f:name: {}
              k:{"name":"OPENSHIFT_DNS_PING_SERVICE_NAME"}:
                ".": {}
                f:name: {}
                f:value: {}
              k:{"name":"OPENSHIFT_DNS_PING_SERVICE_PORT"}:
                ".": {}
                f:name: {}
                f:value: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:livenessProbe:
              ".": {}
              f:exec:
                ".": {}
                f:command: {}
              f:failureThreshold: {}
              f:initialDelaySeconds: {}
              f:periodSeconds: {}
              f:successThreshold: {}
              f:timeoutSeconds: {}
            f:name: {}
            f:ports:
              ".": {}
              k:{"containerPort":8080,"protocol":"TCP"}:
                ".": {}
                f:containerPort: {}
                f:name: {}
                f:protocol: {}
              k:{"containerPort":8778,"protocol":"TCP"}:
                ".": {}
                f:containerPort: {}
                f:name: {}
                f:protocol: {}
              k:{"containerPort":8888,"protocol":"TCP"}:
                ".": {}
                f:containerPort: {}
                f:name: {}
                f:protocol: {}
            f:readinessProbe:
              ".": {}
              f:exec:
                ".": {}
                f:command: {}
              f:failureThreshold: {}
              f:initialDelaySeconds: {}
              f:periodSeconds: {}
              f:successThreshold: {}
              f:timeoutSeconds: {}
            f:resources:
              ".": {}
              f:limits:
                ".": {}
                f:memory: {}
              f:requests:
                ".": {}
                f:memory: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext: {}
        f:terminationGracePeriodSeconds: {}
  - manager: "multus"
    operation: "Update"
    apiVersion: "v1"
    time: "2021-07-30T09:43:12Z"
    fieldsType: "FieldsV1"
    fieldsV1:
      f:metadata:
        f:annotations:
          f:k8s.v1.cni.cncf.io/network-status: {}
          f:k8s.v1.cni.cncf.io/networks-status: {}
  - manager: "kubelet"
    operation: "Update"
    apiVersion: "v1"
    time: "2021-07-30T09:43:38Z"
    fieldsType: "FieldsV1"
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            ".": {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            ".": {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            ".": {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          ".": {}
          k:{"ip":"10.131.0.94"}:
            ".": {}
            f:ip: {}
        f:startTime: {}
spec:
  volumes:
  - name: "default-token-jxqc2"
    secret:
      secretName: "default-token-jxqc2"
      defaultMode: 420
  containers:
  - name: "eap-app66"
    image: "image-registry.openshift-image-registry.svc:5000/baik/eap-app66@sha256:6b3e0af5a2b8511f2dbf51f55647618a3ca7fa666deb37418c478c4394545f90"
    ports:
    - name: "jolokia"
      containerPort: 8778
      protocol: "TCP"
    - name: "http"
      containerPort: 8080
      protocol: "TCP"
    - name: "ping"
      containerPort: 8888
      protocol: "TCP"
    env:
    - name: "JGROUPS_PING_PROTOCOL"
      value: "dns.DNS_PING"
    - name: "OPENSHIFT_DNS_PING_SERVICE_NAME"
      value: "eap-app66-ping"
    - name: "OPENSHIFT_DNS_PING_SERVICE_PORT"
      value: "8888"
    - name: "MQ_CLUSTER_PASSWORD"
      value: "h5GBebCK"
    - name: "MQ_QUEUES"
    - name: "MQ_TOPICS"
    - name: "JGROUPS_CLUSTER_PASSWORD"
      value: "ynypBxfn"
    - name: "AUTO_DEPLOY_EXPLODED"
      value: "false"
    - name: "ENABLE_GENERATE_DEFAULT_DATASOURCE"
      value: "false"
    resources:
      limits:
        memory: "1Gi"
      requests:
        memory: "1Gi"
    volumeMounts:
    - name: "default-token-jxqc2"
      readOnly: true
      mountPath: "/var/run/secrets/kubernetes.io/serviceaccount"
    livenessProbe:
      exec:
        command:
        - "/bin/bash"
        - "-c"
        - "/opt/eap/bin/livenessProbe.sh"
      initialDelaySeconds: 60
      timeoutSeconds: 1
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3
    readinessProbe:
      exec:
        command:
        - "/bin/bash"
        - "-c"
        - "/opt/eap/bin/readinessProbe.sh"
      initialDelaySeconds: 10
      timeoutSeconds: 1
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3
    terminationMessagePath: "/dev/termination-log"
    terminationMessagePolicy: "File"
    imagePullPolicy: "Always"
    securityContext:
      capabilities:
        drop:
        - "KILL"
        - "MKNOD"
        - "SETGID"
        - "SETUID"
      runAsUser: 1000580000
  restartPolicy: "Always"
  terminationGracePeriodSeconds: 75
  dnsPolicy: "ClusterFirst"
  serviceAccountName: "default"
  serviceAccount: "default"
  nodeName: "worker02.ocp46.injecloud.co.kr"
  securityContext:
    seLinuxOptions:
      level: "s0:c24,c14"
    fsGroup: 1000580000
  imagePullSecrets:
  - name: "default-dockercfg-4wfpk"
  schedulerName: "default-scheduler"
  tolerations:
  - key: "node.kubernetes.io/not-ready"
    operator: "Exists"
    effect: "NoExecute"
    tolerationSeconds: 300
  - key: "node.kubernetes.io/unreachable"
    operator: "Exists"
    effect: "NoExecute"
    tolerationSeconds: 300
  - key: "node.kubernetes.io/memory-pressure"
    operator: "Exists"
    effect: "NoSchedule"
  priority: 0
  enableServiceLinks: true
  preemptionPolicy: "PreemptLowerPriority"
status:
  phase: "Running"
  conditions:
  - type: "Initialized"
    status: "True"
    lastProbeTime: null
    lastTransitionTime: "2021-07-30T09:43:10Z"
  - type: "Ready"
    status: "True"
    lastProbeTime: null
    lastTransitionTime: "2021-07-30T09:43:38Z"
  - type: "ContainersReady"
    status: "True"
    lastProbeTime: null
    lastTransitionTime: "2021-07-30T09:43:38Z"
  - type: "PodScheduled"
    status: "True"
    lastProbeTime: null
    lastTransitionTime: "2021-07-30T09:43:10Z"
  hostIP: "192.168.62.215"
  podIP: "10.131.0.94"
  podIPs:
  - ip: "10.131.0.94"
  startTime: "2021-07-30T09:43:10Z"
  containerStatuses:
  - name: "eap-app66"
    state:
      running:
        startedAt: "2021-07-30T09:43:19Z"
    lastState: {}
    ready: true
    restartCount: 0
    image: "image-registry.openshift-image-registry.svc:5000/baik/eap-app66@sha256:6b3e0af5a2b8511f2dbf51f55647618a3ca7fa666deb37418c478c4394545f90"
    imageID: "image-registry.openshift-image-registry.svc:5000/baik/eap-app66@sha256:6b3e0af5a2b8511f2dbf51f55647618a3ca7fa666deb37418c478c4394545f90"
    containerID: "cri-o://2871e6a76062377652a867bce4c93f15e90c28cb5cd19b6f4e12fb48573d47b5"
    started: true
  qosClass: "Burstable"
